### ISSUE TITLE
NameError: name 'print_item' is not defined

### ISSUE THREAD

**Issue by Currerius** [Azure-Samples/resource-manager-python-resources-and-groups#6]
When running the the code of from the README, I get a NameError.

`python NameError: name 'print_item' is not defined`

The README states that "there are a couple of supporting functions (print_item and print_properties) that print a resource group and it's properties."

But where are they?

Ah, edit: I found them. They are defined inside the example.py script. Did not catch that.
Solved.

**Comment by lmazuel** [comment]
Sorry if it was unclear :(. I'm glad it finally worked though :)
Thanks
