### ISSUE TITLE
Listing the resources within group not available in new python azure libraries 4.0.0

### ISSUE THREAD

**Issue by rsimac** [Azure-Samples/resource-manager-python-resources-and-groups#7]
While samples here clearly require azure sdk 2.0.0, it may be beneficial to further emphasize the sample will not work with the (current) python azure sdk 4.0.0, at least not the listing of resources within a group.

This sample suggests: `client.resource_groups.list_resources(GROUP_NAME)`

While current/new api for this purpose is: `client.resources.list_by_resource_group(GROUP_NAME)`

Current azure python sdk: https://github.com/Azure/azure-sdk-for-python

Thanks for otherwise excellent samples!

**Comment by lmazuel** [comment]
Hi @rsimac !
Thanks for the feedback on samples :).
I indeed need to update the sample. I add that in my backlog.
Thanks!

**Comment by lmazuel** [comment]
Done in https://github.com/Azure-Samples/resource-manager-python-resources-and-groups/pull/5

**Comment by dparkar** [comment]
Why is this still not in master ?
